import os
import datetime
import webbrowser
import markdown # You might need to install this: pip install markdown

# --- Configuration ---
BLOG_PAGE_PATH = 'index.html'  # Path to your blog posts HTML file
TEMP_PREVIEW_PATH = 'blog-posts-preview.html' # Temporary file for preview
INSERTION_MARKER = '<!-- NEW_BLOG_POST_INSERTION_POINT -->'

# Define pastel tag colors
PASTEL_COLORS = [
    "tag-blue", "tag-green", "tag-pink", "tag-yellow", "tag-purple"
]

def get_tag_class(tag_name, index):
    """Cycles through pastel colors for tags."""
    return PASTEL_COLORS[index % len(PASTEL_COLORS)]

def generate_blog_card_html(title, description, date_str, tags_list):
    """
    Generates the HTML string for a new blog post card.
    """
    tag_spans = []
    for i, tag in enumerate(tags_list):
        tag_class = get_tag_class(tag.strip(), i)
        tag_spans.append(f'                            <span class="pastel-tag {tag_class}">{tag.strip()}</span>')

    tags_html = "\n".join(tag_spans)

    # Note: The 'Read More' link currently points to '#' as full blog post pages are not generated by this script.
    # If you later create individual blog post pages, you'll need to update this href.
    blog_card_html = f"""
                <!-- Blog Post Card - {title} -->
                <div class="blog-card rounded-lg p-6 flex flex-col justify-between">
                    <div>
                        <h3 class="text-xl md:text-2xl font-bold text-white mb-2">{title}</h3>
                        <p class="text-gray-400 text-sm mb-3">Published on: {date_str}</p>
                        <p class="text-gray-300 mb-4 text-base">
                            {description}
                        </p>
                    </div>
                    <div>
                        <div class="flex flex-wrap gap-2 mb-2">
{tags_html}
                        </div>
                        <a href="#" class="text-blue-400 hover:underline text-sm font-medium">Read More &rarr;</a>
                    </div>
                </div>
"""
    return blog_card_html.strip()

def main():
    """Main function for the blog post creation CLI."""
    print("--- Create New Blog Post Entry ---")

    # 1. Get Markdown file path
    markdown_file_path = input("Enter the path to your Markdown file (e.g., my_post.md): ").strip()
    if not os.path.exists(markdown_file_path):
        print(f"Error: File not found at '{markdown_file_path}'. Please check the path.")
        return

    try:
        with open(markdown_file_path, 'r', encoding='utf-8') as f:
            markdown_content = f.read()
    except Exception as e:
        print(f"Error reading Markdown file: {e}")
        return

    # 2. Get metadata from user
    title = input("Enter the blog post title: ").strip()
    if not title:
        print("Title cannot be empty. Aborting.")
        return

    description = input("Enter a short card description (e.g., 2-3 sentences): ").strip()
    if not description:
        print("Description cannot be empty. Aborting.")
        return

    tags_input = input("Enter tags (comma-separated, e.g., Python, Web Dev, AI): ").strip()
    tags_list = [tag.strip() for tag in tags_input.split(',') if tag.strip()]

    # 3. Automatic date
    publish_date = datetime.datetime.now().strftime("%B %d, %Y")

    # Convert markdown content to HTML (though not directly used in the card snippet)
    # This would be useful if you later create full individual blog post pages.
    # full_post_html_content = markdown.markdown(markdown_content)

    # Generate the new blog card HTML
    new_blog_card = generate_blog_card_html(title, description, publish_date, tags_list)

    # --- Preview Logic ---
    try:
        with open(BLOG_PAGE_PATH, 'r', encoding='utf-8') as f:
            blog_page_content = f.read()

        if INSERTION_MARKER not in blog_page_content:
            print(f"Error: Insertion marker '{INSERTION_MARKER}' not found in '{BLOG_PAGE_PATH}'.")
            print("Please add this marker inside the <div class=\"grid ...\"> section of your HTML file.")
            return

        # Create temporary content with the new post for preview
        preview_content = blog_page_content.replace(INSERTION_MARKER, new_blog_card + '\n' + INSERTION_MARKER, 1)

        with open(TEMP_PREVIEW_PATH, 'w', encoding='utf-8') as f:
            f.write(preview_content)

        print(f"\nPreview generated: '{TEMP_PREVIEW_PATH}'")
        webbrowser.open(f"file://{os.path.abspath(TEMP_PREVIEW_PATH)}")

        # --- Publish Logic ---
        publish_choice = input("Do you want to publish this post to your blog page? (yes/no): ").strip().lower()

        if publish_choice == 'yes':
            final_content = blog_page_content.replace(INSERTION_MARKER, new_blog_card + '\n' + INSERTION_MARKER, 1)
            with open(BLOG_PAGE_PATH, 'w', encoding='utf-8') as f:
                f.write(final_content)
            print(f"Successfully published '{title}' to '{BLOG_PAGE_PATH}'!")
        else:
            print("Post not published. Preview file will be deleted.")

    except FileNotFoundError:
        print(f"Error: '{BLOG_PAGE_PATH}' not found. Make sure the file exists in the same directory.")
    except Exception as e:
        print(f"An unexpected error occurred during preview/publish: {e}")
    finally:
        # Clean up temporary preview file
        if os.path.exists(TEMP_PREVIEW_PATH):
            os.remove(TEMP_PREVIEW_PATH)
            print(f"Cleaned up temporary preview file: '{TEMP_PREVIEW_PATH}'")

if __name__ == '__main__':
    main()
